AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infraestrutura AWS'

Parameters:
  ProjectName:
    Type: String
    Default: 'pipeline-devops'
    Description: 'Nome do projeto'
  
  Environment:
    Type: String
    Default: 'prod'
    Description: 'Ambiente de deploy'

  NotificationEmail:
    Type: String
    Description: 'Email para receber alertas de monitoramento'
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

Resources:
  # ===== BUCKET PARA O SITE =====
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-website-${Environment}-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Política do bucket para acesso público de leitura
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: WebsiteBucket
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'

  # ===== MONITORAMENTO SIMPLES =====
  # SNS Topic para alertas
  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-alerts-${Environment}'
      DisplayName: 'Alertas Simples de Monitoramento'

  AlertsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlertsTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

  # Alarme de CPU > 70%
  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-high-cpu-${Environment}'
      AlarmDescription: 'Alarme quando CPU excede 70%'
      MetricName: 'CPUUtilization'
      Namespace: 'AWS/EC2'
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching

  # Alarme de Memória > 70%
  HighMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-high-memory-${Environment}'
      AlarmDescription: 'Alarme quando Memória excede 70%'
      MetricName: 'MemoryUtilization'
      Namespace: 'CWAgent'
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching

Outputs:
  WebsiteBucketName:
    Description: 'Nome do bucket S3 para website'
    Value: !Ref WebsiteBucket

  WebsiteURL:
    Description: 'URL do website hospedado no S3'
    Value: !GetAtt WebsiteBucket.WebsiteURL

  AlertsTopicArn:
    Description: 'ARN do tópico SNS para alertas'
    Value: !Ref AlertsTopic
