name: CI

on:
   push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Executa o CI
        run: echo "CI executado com sucesso!"

      - name: Instala o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instala as dependencias
        run: npm install

      - name: Executa testes
        run: npm test

      - name: Mensagem de sucesso
        run: echo "Todos os testes passaram com sucesso!"
